site_name: kepler-apertures
nav:
    - Home: index.md
    - KeplerFFI: KeplerFFI.md
    - KeplerPRF : KeplerPRF.md
    - EXBAMachine : EXBAMachine.md
    - Tutorials : create_PRF_tutorial.ipynb
theme:
  name: "material"
repo_url: https://github.com/jorgemarpa/kepler-apertures
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: "numpy"
          rendering:
            show_source: false
      custom_templates: templates
      watch:
        - src/my_package
  - mkdocs-jupyter:
      ignore_h1_titles: True
      execute: False
      include_source: True
